In [2]:
import numpy as np

In [ ]:
ohlc_data_day1 = np.array([
    [100.0, 101.5, 99.5, 101.0],
    [101.0, 102.0, 100.5, 101.8],
    [101.8, 103.0, 101.0, 102.5]
])

ohlc_data_day2 = np.array([
    [200.0, 201.5, 199.5, 201.0],
    [201.0, 202.0, 200.5, 201.8],
    [201.8, 203.0, 201.0, 202.5]
])

## Min/Max/Sum/Product in NumPy arrays

In [6]:
np.min(ohlc_data_day1)

np.float64(99.5)

In [7]:
np.max(ohlc_data_day2)

np.float64(203.0)

In [8]:
np.sum(ohlc_data_day1)

np.float64(1215.6)

In [14]:
np.prod(ohlc_data_day2)

np.float64(4.4265487763544875e+27)

Scalar Multiplication

In [15]:
ohlc_data_day1 * 2

array([[200. , 203. , 199. , 202. ],
       [202. , 204. , 201. , 203.6],
       [203.6, 206. , 202. , 205. ]])

Vector Multiplication

In [16]:
ohlc_data_day1 * ohlc_data_day2

array([[20000.  , 20452.25, 19850.25, 20301.  ],
       [20301.  , 20604.  , 20150.25, 20543.24],
       [20543.24, 20909.  , 20301.  , 20756.25]])

## Mean/ Median/ Standard Deviation/ Variance

In [21]:
print(np.mean(ohlc_data_day1))
print(np.mean(ohlc_data_day2))

101.3
201.29999999999998


In [22]:
print(np.median(ohlc_data_day1))
print(np.median(ohlc_data_day2))

101.25
201.25


In [23]:
print(np.std(ohlc_data_day1))
print(np.std(ohlc_data_day2))

0.9660917830792956
0.9660917830792968


In [24]:
print(np.var(ohlc_data_day1))
print(np.var(ohlc_data_day2))

0.9333333333333327
0.933333333333335


## Trignometric Functions in NumPy

In [25]:
np.sin(ohlc_data_day1)

array([[-0.50636564,  0.82433986, -0.85779535,  0.45202579],
       [ 0.45202579,  0.99482679, -0.03095997,  0.95481453],
       [ 0.95481453,  0.62298863,  0.45202579,  0.92174542]])

## Dot Product in NumPy Arrays

In [26]:
mat1 = np.array([
    [100.0, 101.5, 99.5, 101.0],
    [101.0, 102.0, 100.5, 101.8],
    [101.8, 103.0, 101.0, 102.5]
])

mat2 = np.array([
    [100.0, 101.5, 99.5, 101.0],
    [101.0, 102.0, 100.5, 101.8],
    [101.8, 103.0, 101.0, 102.5],
    [101.8, 103.0, 101.0, 102.5]
])

In [27]:
np.dot(mat1, mat2)

array([[40662.4 , 41154.5 , 40401.25, 40983.95],
       [40996.14, 41492.4 , 40732.8 , 41320.35],
       [41299.3 , 41799.2 , 41034.1 , 41625.95]])

For dot product, we need to make sure that column of first matrix array should match with the row of second matrix 
In above case mat1 has 4 columns,  and second matrix has 4 rows, so dot product is possible and size would be 3*4.

## Log and Exponential Values in NumPy

In [28]:
np.exp(ohlc_data_day1)

array([[2.68811714e+43, 1.20473052e+44, 1.63042546e+43, 7.30705998e+43],
       [7.30705998e+43, 1.98626484e+44, 4.43195591e+43, 1.62621611e+44],
       [1.62621611e+44, 5.39922761e+44, 7.30705998e+43, 3.27479708e+44]])

In [29]:
np.log(ohlc_data_day2)

array([[5.29831737, 5.30578938, 5.29581424, 5.30330491],
       [5.30330491, 5.3082677 , 5.30081425, 5.30727711],
       [5.30727711, 5.31320598, 5.30330491, 5.31073989]])

## Round, Floor and Ceil in NumPy

In [30]:
np.round(ohlc_data_day1)

array([[100., 102., 100., 101.],
       [101., 102., 100., 102.],
       [102., 103., 101., 102.]])

In [31]:
np.floor(ohlc_data_day2)

array([[200., 201., 199., 201.],
       [201., 202., 200., 201.],
       [201., 203., 201., 202.]])

In [32]:
np.ceil(ohlc_data_day1)

array([[100., 102., 100., 101.],
       [101., 102., 101., 102.],
       [102., 103., 101., 103.]])

## SLICING IN 3D- NumPy Array

In [13]:
ThreeDArray = np.arange(1,25).reshape(2,3,4)
ThreeDArray

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [7]:
ThreeDArray[1,:,2:]

array([[15, 16],
       [19, 20],
       [23, 24]])

## Iterating values in Matrix

In [10]:
for i in np.nditer(ThreeDArray):
    print(i, end=",")

1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,

In [11]:
for i in np.ravel(ThreeDArray):
    print(i, end=",")

1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,

##  Transpose

In [14]:
np.transpose(ThreeDArray)

array([[[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]],

       [[ 4, 16],
        [ 8, 20],
        [12, 24]]])

In [15]:
ThreeDArray.T

array([[[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]],

       [[ 4, 16],
        [ 8, 20],
        [12, 24]]])

## Horizontal and Vertical Stacking in NumPy array

### Horizontal Scaling

In [19]:
ohlc_data_day1 = np.array([
    [100.0, 101.5, 99.5, 101.0],
    [101.0, 102.0, 100.5, 101.8],
    [101.8, 103.0, 101.0, 102.5]
])

ohlc_data_day2 = np.array([
    [200.0, 201.5, 199.5, 201.0],
    [201.0, 202.0, 200.5, 201.8],
    [201.8, 203.0, 201.0, 202.5]
])

In [20]:
np.hstack((ohlc_data_day1, ohlc_data_day2))

array([[100. , 101.5,  99.5, 101. , 200. , 201.5, 199.5, 201. ],
       [101. , 102. , 100.5, 101.8, 201. , 202. , 200.5, 201.8],
       [101.8, 103. , 101. , 102.5, 201.8, 203. , 201. , 202.5]])

### Vertical Scaling

In [21]:
np.vstack((ohlc_data_day1, ohlc_data_day2))

array([[100. , 101.5,  99.5, 101. ],
       [101. , 102. , 100.5, 101.8],
       [101.8, 103. , 101. , 102.5],
       [200. , 201.5, 199.5, 201. ],
       [201. , 202. , 200.5, 201.8],
       [201.8, 203. , 201. , 202.5]])

## Splitting

### Horizontal Splitting

In [22]:
horizon = np.hstack((ohlc_data_day1, ohlc_data_day2))

In [23]:
np.hsplit(horizon, 2)

[array([[100. , 101.5,  99.5, 101. ],
        [101. , 102. , 100.5, 101.8],
        [101.8, 103. , 101. , 102.5]]),
 array([[200. , 201.5, 199.5, 201. ],
        [201. , 202. , 200.5, 201.8],
        [201.8, 203. , 201. , 202.5]])]

### Vertical Splitting

In [24]:
vertical = np.vstack((ohlc_data_day1, ohlc_data_day2))

In [25]:
np.vsplit(vertical, 2)

[array([[100. , 101.5,  99.5, 101. ],
        [101. , 102. , 100.5, 101.8],
        [101.8, 103. , 101. , 102.5]]),
 array([[200. , 201.5, 199.5, 201. ],
        [201. , 202. , 200.5, 201.8],
        [201.8, 203. , 201. , 202.5]])]