In [55]:
import numpy as np

In [56]:
np.array([1,2,3,4,5,6,7,8,9])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
vari = np.array([1,2,3,4,5,6,8,9,7,10,11,12], dtype=str)
print(vari)

['1' '2' '3' '4' '5' '6' '8' '9' '7' '10' '11' '12']


In [58]:
print(type(vari))

<class 'numpy.ndarray'>


In [59]:
vari.reshape(2,2,3)

array([[['1', '2', '3'],
        ['4', '5', '6']],

       [['8', '9', '7'],
        ['10', '11', '12']]], dtype='<U2')

## Arange method 

In [60]:
np.arange(0,12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [61]:
print(type(np.arange(0,12)))

<class 'numpy.ndarray'>


In [62]:
np.arange(0,12).reshape(2,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

## np.ones and np.zeros method 

In [63]:
var = np.ones((2,2,3),np.int32)
var

array([[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]], dtype=int32)

In [64]:
print(type(var))

<class 'numpy.ndarray'>


In [65]:
np.ones((5,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [66]:
np.zeros((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

## Random Module in NumPY

In [67]:
np.random.random(5)*100

array([73.2174178 , 39.71446248, 19.19352139, 25.70935388, 58.63737837])

In [68]:
np.random.random((2,6))*100

array([[27.32436051, 70.61767978, 32.65812626, 12.29329939,  7.15583618,
        69.02141969],
       [93.68820901,  2.88373003, 61.21343081,  1.53286836, 99.28554329,
        87.44780985]])

## Linspace method 

In [69]:
np.linspace(1,2,5)

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [70]:
np.linspace(1,10,9)

array([ 1.   ,  2.125,  3.25 ,  4.375,  5.5  ,  6.625,  7.75 ,  8.875,
       10.   ])

Linspace method in numpy is like arithmetic progression(AP) because it provides you numbers having equal difference between each other.
It takes two to three arguments in which first one denotes starting point, second one denotes ending point and third one denoted total numbers of points we needed. this is specified in above example clearly.

## Identity Matrices in NumPy

In [74]:
np.identity(2,np.int32)

array([[1, 0],
       [0, 1]], dtype=int32)

In [75]:
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])