In [1]:
import numpy as np

In [19]:
ohlc1 = np.array([200.0, 201.5, 199.5, 201.0, 201.8, 203.0, 201.0, 202.5])


ohlc2 = np.array([
    [200.0, 201.5, 199.5, 208.0],
    [201.0, 202.0, 200.5, 201.8],
    [201.8, 203.0, 201.0, 202.5]
])

In [17]:
np.sort(ohlc1)[::-1]      # descending order sorting
np.sort(ohlc1)            # ascending order sorting

array([199.5, 200. , 201. , 201. , 201.5, 201.8, 202.5, 203. ])

In [ ]:
np.sort(ohlc2, axis=1)    # sorts row-wise values
np.sort(ohlc2, axis=0)    # sorts column-wise values

array([[200. , 201.5, 199.5, 201.8],
       [201. , 202. , 200.5, 202.5],
       [201.8, 203. , 201. , 208. ]])

In [20]:
np.append(ohlc1, 500.0)

array([200. , 201.5, 199.5, 201. , 201.8, 203. , 201. , 202.5, 500. ])

In [28]:
np.append(ohlc2, np.arange(4).reshape(1,4), axis = 0)     # appends values onto rows in 2-d numpy array

array([[200. , 201.5, 199.5, 208. ],
       [201. , 202. , 200.5, 201.8],
       [201.8, 203. , 201. , 202.5],
       [  0. ,   1. ,   2. ,   3. ]])

In [29]:
np.append(ohlc2, np.arange(3).reshape(3,1), axis = 1)     # appends values onto columns in 2-d numpy array

array([[200. , 201.5, 199.5, 208. ,   0. ],
       [201. , 202. , 200.5, 201.8,   1. ],
       [201.8, 203. , 201. , 202.5,   2. ]])